Replace align attribute for P and IMG elements
InteractiveIntelligence/Squire pull request #78
Opened 2016-10-12 02:39 UTC by ruiliuinin

2016-10-12 03:09 UTC, akauffmanGG requested changes
I'm assuming these changes are so that we can get the alignment buttons to show correctly. If so, this seems like overkill to add an alignment class to each block, p, and img.

2016-10-12 03:09 UTC, akauffmanGG commented on build/squire-raw.js
> +                wrapper.className = ( wrapper.className
Use the _addAlignClassName function here

2016-10-12 03:09 UTC, akauffmanGG commented on build/squire-raw.js
> +        if ( node.tagName.toUpperCase() === 'P' ) {
This code is duplicated for both IMG and P elements. Can we just extract this into a separate function? Something like fixAlignmentAttributes.

2016-10-12 18:34 UTC, ruiliuinin commented on build/squire-raw.js
> +        if ( node.tagName.toUpperCase() === 'P' ) {
P and IMG are slightly different. IMG elements will be wrapped up in DIV so the new align class is added to div and the align attribute is removed from IMG. P elements don't need to wrapped put in DIV so the new classed in added to P. Added a new function _getAlignment to reuse the code in common between these two.

2016-10-12 18:39 UTC, ruiliuinin commented
It needs to have an alignment class to each block, p, and img to make sure the path is changed like changing from 'DIV>P.alignment-left' to  'DIV>P.alignment-right'. If we don't have the alignment class, both paths will be "DIV>P". It won't be able to tell the path changed when the cursor moves between such elements.

2016-10-14 12:58 UTC, akauffmanGG commented
Ok. I don't feel great about adding an alignment class everywhere. We should look to see if maybe we could only add it when it's different from the body dir or something like that.

2016-10-14 12:58 UTC, merged